---

- ansible.builtin.import_tasks: install.yml

- ansible.builtin.import_tasks: configure.yml

# Removed this task as mailgraph does not have a 'status' check on it's init script.
# - name: Ensure Mailgraph is started
#   ansible.builtin.service:
#     name: mailgraph
#     state: started
#     enabled: true
